language: python

matrix:
    include:
      - python: "2.7"
        os: linux
      - python: "3.2"
        os: linux
      - python: "3.3"
        os: linux
      - python: "3.4"
        os: linux
      - python: "3.5"
        os: linux
      - os: osx
        language: generic

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install --quiet git+https://github.com/myint/cram.git || cat /Users/travis/Library/logs/pip.log; fi
   - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then      pip install --quiet git+https://github.com/myint/cram.git; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo python setup.py --quiet install; fi
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then      python setup.py --quiet install; fi

script:
    - uname -a
    - cram --indent=4 test.cram
